/*
 * message_structs.h
 *
 *  Created on: Feb 7, 2017
 *      Author: lscholte
 */

#ifndef SOURCES_MESSAGE_STRUCTS_H_
#define SOURCES_MESSAGE_STRUCTS_H_


#define CHAR_MESSAGE_TYPE 0
#define STRING_MESSAGE_TYPE 1

#define TASK_CREATION_MESSAGE_TYPE 2
#define TASK_DELETION_MESSAGE_TYPE 3
#define ACTIVE_TASK_REQUEST_MESSAGE_TYPE 4
#define OVERDUE_TASK_REQUEST_MESSAGE_TYPE 5
#define TASK_LIST_MESSAGE_TYPE 6

typedef struct string_message {
	MESSAGE_HEADER_STRUCT HEADER;
	int TYPE;
	char DATA[BUFFER_LENGTH_WITH_NULL];
} STRING_MESSAGE, * STRING_MESSAGE_PTR;

typedef struct {
	MESSAGE_HEADER_STRUCT HEADER;
	int TYPE;
	void* DATA_PTR;
} GENERIC_MESSAGE, * GENERIC_MESSAGE_PTR;

typedef struct {
	_task_id TASK_ID;
	uint32_t DEADLINE;
} TASK_CREATION_DATA, * TASK_CREATION_DATA_PTR;

typedef struct {
	_task_id TASK_ID;
} TASK_DELETION_DATA, * TASK_DELETION_DATA_PTR;

typedef struct {
	TASK_LIST TASK_LIST;
} TASK_LIST_DATA, * TASK_LIST_DATA_PTR;

#endif /* SOURCES_MESSAGE_STRUCTS_H_ */
